### PR TITLE
fixes assigned_route charts to actually order by grade even if there …

### LINKED ISSUE #165: assigned routes charts x-axis is unordered
it's supposed to be a stacked bar chart ordered by rating of route, but they're all out of order. looks dumb.

### PR DESCRIPTION
**Pull request by skeltont**
…are no valid routes under certain grade / statuses

fixes #165

### CODE REVIEW

File: app/controllers/admin/charts_controller.rb [hunk 1]
```diff
@@ -1,33 +1,44 @@
 module Admin
   class ChartsController < ApplicationController
-
     def routes
-      butts = [
```
Comment (jonahgeorge) [inline app/controllers/admin/charts_controller.rb:5]: wtf this was actually committed :trollface:
